root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  backend = "go build -o tmp/main main.go"
  include = ["*.go"]
  exclude = ["tmp", "vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  log = "white"