CREATE TABLE companies (
    id CHAR(36) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL UNIQUE,
    tin CHAR(25) NOT NULL,
    email VARCHAR(255) NOT NULL,3
    address TEXT,
    phone VARCHAR(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id CHAR(36) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    company_id CHAR(36) NOT NULL,
    company_tin CHAR(25),
    -- role VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP ON DELETE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_tin) REFERENCES companies(tin)
);


